<?php

    function findAllApprenant($promotion){
 
        $apprenants = [
            [
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
                
            ],
            [
                'image' => 'man.png',
                'nom' => 'Seck',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 2, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbaye',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772211300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Sow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 2, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Dieng',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 2, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Fall',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 2, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Diop',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Diop',
                'prenom' => 'Adama',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772282211', 
                'action' => "",
            ],
            [
                'image' => 'teste.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Saer Wade',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '773383300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            'idPromotion' => 6
        ],
        [
            [
                'image' => 'man.png',
                'nom' => 'Mbow promo5',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
                
            ],
            [
                'image' => 'man.png',
                'nom' => 'Seck',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 2, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbaye',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772211300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Sow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 2, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Dieng',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 2, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Fall',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 2, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Diop',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Diop',
                'prenom' => 'Adama',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772282211', 
                'action' => "",
            ],
            [
                'image' => 'teste.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Saer Wade',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '773383300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Last promo5',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            'idPromotion' => 5
        ],
        [
            [
                'image' => 'man.png',
                'nom' => 'Mbow promo4',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
                
            ],
            [
                'image' => 'man.png',
                'nom' => 'Seck',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 2, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbaye',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772211300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Sow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 2, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Dieng',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 2, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Fall',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 2, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Diop',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Diop',
                'prenom' => 'Adama',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772282211', 
                'action' => "",
            ],
            [
                'image' => 'teste.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Saer Wade',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '773383300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Mbow',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            [
                'image' => 'man.png',
                'nom' => 'Last promo4',
                'prenom' => 'Baye Saer',
                'email' => 'mbowbayesaer44@6gmail.com',
                'genre' => 1, 
                'telephone' => '772283300', 
                'action' => "",
            ],
            'idPromotion' => 4
        ]
    ];
        
    foreach($apprenants as $apprenant_list){
        if($apprenant_list['idPromotion'] == $promotion){
           return array_slice($apprenant_list, 0, -1);
        }
    }
    return [];
    }
    

    function findAllApprenantFiltre($search = null, $apprenants){
        $apprenantsFilter = [];
        // dd($search);
        if($search != null){
                $apprenantsFilter = array_filter($apprenants, function($value) use($search){
                    return $value['nom'] === $search || $value['prenom'] === $search 
                    || $value['email'] === $search || $value['telephone'] === $search; 
                });
                
                $apprenantsFilter = array_values($apprenantsFilter);
    
        }
        $apprenantsFilter = array_values($apprenantsFilter);
        return $apprenantsFilter;
        
    }

?>